SET FOREIGN_KEY_CHECKS=1;
COMMIT;

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS FOOD_ITEMS;
DROP TABLE IF EXISTS FOOD_ITEMS_ORDERS;
DROP TABLE IF EXISTS RESTAURANTS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE RESTAURANTS (
RESTAURANT_ID INT(11) AUTO_INCREMENT NOT NULL,
RATING DECIMAL NOT NULL,
NAME VARCHAR(255) NOT NULL,
PHONE_NUMBER INT(11),
ADDRESS VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255),
PRIMARY KEY (RESTAURANT_ID)
);

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT(11) AUTO_INCREMENT NOT NULL,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
PHONE_NUMBER INT(11),
ADDRESS VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS (
ORDER_ID INT(11) AUTO_INCREMENT NOT NULL,
ORDER_DATE DATE NOT NULL,
CUSTOMER_ID INT(11) NOT NULL,
RESTAURANT_ID INT(11) NOT NULL,
TOTAL_PRICE DECIMAL NOT NULL,
PAYMENT_STATUS BOOLEAN NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID),
PRIMARY KEY (ORDER_ID)
);

CREATE TABLE FOOD_ITEMS (
FOOD_ITEM_ID INT(11) AUTO_INCREMENT NOT NULL,
RESTAURANT_ID INT(11) NOT NULL,
NAME VARCHAR(255) NOT NULL,
PRICE DECIMAL(6,2)  NOT NULL,
FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID),
PRIMARY KEY (FOOD_ITEM_ID)
);

CREATE TABLE FOOD_ITEMS_ORDERS (
FOOD_ITEM_ID INT(11) NOT NULL,
ORDER_ID INT(11) NOT NULL,
FOREIGN KEY (FOOD_ITEM_ID) REFERENCES FOOD_ITEMS(FOOD_ITEM_ID),
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
PRIMARY KEY (ORDER_ID, FOOD_ITEM_ID)
);


SET FOREIGN_KEY_CHECKS=1;
COMMIT;
