-- DDL Group 77

DROP PROCEDURE IF EXISTS sp_load_nnndb;
DELIMITER //
CREATE PROCEDURE sp_load_nnndb()
BEGIN

    SET FOREIGN_KEY_CHECKS=0;
    SET AUTOCOMMIT = 0;

    DROP TABLE IF EXISTS ORDERS;
    DROP TABLE IF EXISTS FOOD_ITEMS;
    DROP TABLE IF EXISTS FOOD_ITEMS_ORDERS;
    DROP TABLE IF EXISTS RESTAURANTS;
    DROP TABLE IF EXISTS CUSTOMERS;

    CREATE TABLE RESTAURANTS (
        RESTAURANT_ID INT(11) AUTO_INCREMENT NOT NULL,
        RATING DECIMAL NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        PHONE_NUMBER VARCHAR(10),
        ADDRESS VARCHAR(255) NOT NULL,
        EMAIL VARCHAR(255),
        PRIMARY KEY (RESTAURANT_ID)
    );

    CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT(11) AUTO_INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(10),
    ADDRESS VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
    );

    CREATE TABLE ORDERS (
        ORDER_ID INT(11) AUTO_INCREMENT NOT NULL,
        ORDER_DATE DATE NOT NULL,
        CUSTOMER_ID INT(11) NOT NULL,
        RESTAURANT_ID INT(11) NOT NULL,
        TOTAL_PRICE DECIMAL NOT NULL,
        PAYMENT_STATUS BOOLEAN NOT NULL,
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE ON UPDATE CASCADE,
        PRIMARY KEY (ORDER_ID)
    );

    CREATE TABLE FOOD_ITEMS (
        FOOD_ITEM_ID INT(11) AUTO_INCREMENT NOT NULL,
        RESTAURANT_ID INT(11) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        PRICE DECIMAL(6,2)  NOT NULL,
        FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE ON UPDATE CASCADE,
        PRIMARY KEY (FOOD_ITEM_ID)
    );

    CREATE TABLE FOOD_ITEMS_ORDERS (
    FOOD_ITEM_ID INT(11) NOT NULL,
    ORDER_ID INT(11) NOT NULL,
    FOREIGN KEY (FOOD_ITEM_ID) REFERENCES FOOD_ITEMS(FOOD_ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (ORDER_ID, FOOD_ITEM_ID)
    );

    INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, PHONE_NUMBER, ADDRESS, EMAIL)
    VALUES
        ('Joe', 'Schmo', '5036872456', '1 Happy St, Corvallis, OR 97330', 'joeschmo@gmail.com'),
        ('Sarah', 'Gavonel', '5031948388', '434 Constant Ave, Corvallis, OR 97330', 'sarahgavonel@yahoo.com'),
        ('Fatima', 'Khan', '5034575642', '935 MLK Way, Corvallis, OR 97330', 'fatimakhan@gmail.com');

    INSERT INTO RESTAURANTS (RATING, NAME, PHONE_NUMBER, ADDRESS, EMAIL)
    VALUES
        (4.2, 'Duffies', '5032354485', '123 NW Jackson Ave, Corvallis, OR 97330', 'duffies@aol.net'),
        (4.8, 'Razorback Pit BBQ', '5031235489', '1569 NW Monroe Ave, Corvallis, OR 97330', 'razorbackbbq@razor.com'),
        (3.3, 'McDonalds', '5038763365', '300 NW 3rd St, Corvallis, OR 97330', NULL);

    INSERT INTO FOOD_ITEMS (RESTAURANT_ID, NAME, PRICE)
    VALUES
        ((SELECT RESTAURANT_ID FROM RESTAURANTS WHERE RESTAURANTS.NAME = 'Duffies'), 'Hamburger', 8.99),
        ((SELECT RESTAURANT_ID FROM RESTAURANTS WHERE RESTAURANTS.NAME = 'Razorback Pit BBQ'), 'Ribs', 15.99),
        ((SELECT RESTAURANT_ID FROM RESTAURANTS WHERE RESTAURANTS.NAME = 'McDonalds'), 'French Fries', 3.99);

    INSERT INTO ORDERS (ORDER_DATE, CUSTOMER_ID, RESTAURANT_ID, TOTAL_PRICE, PAYMENT_STATUS)
    VALUES 
        ('2026-01-03', (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMERS.FIRST_NAME = 'Sarah' AND CUSTOMERS.LAST_NAME = 'Gavonel'),
            (SELECT RESTAURANT_ID FROM RESTAURANTS WHERE RESTAURANTS.NAME = 'Razorback Pit BBQ'),15.99, TRUE),
        ('2026-01-09', (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMERS.FIRST_NAME = 'Fatima' AND CUSTOMERS.LAST_NAME = 'Khan'),
            (SELECT RESTAURANT_ID FROM RESTAURANTS WHERE RESTAURANTS.NAME = 'Razorback Pit BBQ'), 15.99, TRUE),
        ('2026-01-10', (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMERS.FIRST_NAME = 'Joe' AND CUSTOMERS.LAST_NAME = 'Schmo'),
            (SELECT RESTAURANT_ID FROM RESTAURANTS WHERE RESTAURANTS.NAME = 'Duffies'), 8.99, TRUE);

    INSERT INTO FOOD_ITEMS_ORDERS (FOOD_ITEM_ID, ORDER_ID)
    VALUES
        ((SELECT FOOD_ITEM_ID FROM FOOD_ITEMS WHERE FOOD_ITEMS.NAME = 'Ribs'), (SELECT ORDER_ID FROM ORDERS JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
            WHERE CUSTOMERS.FIRST_NAME = 'Sarah')),
        ((SELECT FOOD_ITEM_ID FROM FOOD_ITEMS WHERE FOOD_ITEMS.NAME = 'Ribs'), (SELECT ORDER_ID FROM ORDERS JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
            WHERE CUSTOMERS.FIRST_NAME = 'Fatima')),
        ((SELECT FOOD_ITEM_ID FROM FOOD_ITEMS WHERE FOOD_ITEMS.NAME = 'Hamburger'), (SELECT ORDER_ID FROM ORDERS JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
            WHERE CUSTOMERS.FIRST_NAME = 'Joe'));


    -- SHOW TABLES;
    -- SELECT * FROM FOOD_ITEMS_ORDERS
    --   INNER JOIN ORDERS ON ORDERS.ORDER_ID = FOOD_ITEMS_ORDERS.ORDER_ID
    --   INNER JOIN CUSTOMERS ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

    SET FOREIGN_KEY_CHECKS=1;
    COMMIT;
END //

DELIMITER ;