--CUSTOMERS
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, ADDRESS, EMAIL 
FROM CUSTOMERS;

--RESTAURANTS
SELECT RESTAURANT_ID, RATING, NAME, PHONE_NUMBER, ADDRESS, EMAIL 
FROM RESTAURANTS;

--ORDERS
SELECT ORDERS.ORDER_ID, ORDER_DATE, CUSTOMERS.FIRST_NAME, CUSTOMERS.LAST_NAME,
RESTAURANTS.NAME, FOOD_ITEMS.NAME, FOOD_ITEMS.PRICE
FROM ORDERS
LEFT JOIN FOOD_ITEMS_ORDERS 
ON ORDERS.ORDER_ID = FOOD_ITEMS_ORDERS.ORDER_ID
LEFT JOIN FOOD_ITEMS 
ON FOOD_ITEMS.FOOD_ITEM_ID = FOOD_ITEMS_ORDERS.FOOD_ITEM_ID
LEFT JOIN RESTAURANTS 
ON FOOD_ITEMS.RESTAURANT_ID = RESTAURANTS.RESTAURANT_ID
LEFT JOIN CUSTOMERS 
ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

--FOOD_ITEMS
SELECT FOOD_ITEMS.FOOD_ITEM_ID, RESTAURANTS.NAME, FOOD_ITEMS.NAME, FOOD_ITEMS.PRICE
FROM FOOD_ITEMS 
LEFT JOIN RESTAURANTS 
ON RESTAURANTS.RESTAURANT_ID = FOOD_ITEMS.RESTAURANT_ID;

INSERT INTO FOOD_ITEMS (RESTAURANT_ID, NAME, PRICE) VALUES (:RESTAURANT_ID, :NAME, :PRICE);

UPDATE FOOD_ITEMS SET RESTAURANT_ID=:RESTAURANT_ID, FOOD_ITEM_ID=:FOOD_ITEM_ID,
NAME=:NAME, PRICE=:PRICE 
WHERE FOOD_ITEM_ID=:FOOD_ITEM_ID_TO_UPDATE;

--Since the relationship requires a join, deleting a food item deletes all orders depending on/containing that food item
DELETE FROM FOOD_ITEMS_ORDERS 
WHERE FOOD_ITEM_ID = :FOOD_ITEM_ID_FROM_FORM;

DELETE FROM FOOD_ITEMS 
WHERE FOOD_ITEM_ID = :FOOD_ITEM_ID_FROM_FORM;