-- Delete a food item
DROP PROCEDURE IF EXISTS DELETE_FOOD_ITEM;
DELIMITER //

CREATE PROCEDURE DELETE_FOOD_ITEM(
    IN p_foodItemId INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error deleting food item';
    END;
    
    START TRANSACTION;
    
    -- Delete all instances of the food item in the intersection table
    DELETE FROM FOOD_ITEMS_ORDERS
    WHERE FOOD_ITEM_ID = p_foodItemId;
    -- WHERE ORDER_ID IN (SELECT ORDER_ID FROM FOOD_ITEM_ORDERS WHERE FOOD_ITEM_ID = p_foodItemId);
       
    -- Delete the food item itself
    DELETE FROM FOOD_ITEMS 
    WHERE FOOD_ITEM_ID = p_foodItemId;
    
    COMMIT;
END //


-- Delete an order
DROP PROCEDURE IF EXISTS DELETE_ORDER_FOOD_ITEM;
DELIMITER //

CREATE PROCEDURE DELETE_ORDER_FOOD_ITEM(
    IN p_orderId INT,
    IN p_foodId INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error deleting order';
    END;
    
    START TRANSACTION;
    
    -- Delete all instances of the order in the intersection table
    DELETE FROM FOOD_ITEMS_ORDERS
    WHERE (ORDER_ID = p_orderId AND FOOD_ITEM_ID = p_foodId);
    -- WHERE FOOD_ITEM_ID IN (SELECT FOOD_ITEM_ID FROM FOOD_ITEM_ORDERS WHERE ORDER_ID = p_orderId);
       
    -- Delete the order itself
    -- DELETE FROM ORDERS 
    -- WHERE ORDER_ID = p_orderId;
    
    COMMIT;
END //

-- Create a food item
DROP PROCEDURE IF EXISTS CREATE_FOOD_ITEM;
DELIMITER //

CREATE PROCEDURE CREATE_FOOD_ITEM(
    IN RESTAURANT_ID_IN INT,
    IN FOOD_NAME_IN VARCHAR(255),
    IN PRICE_IN DECIMAL(6,2)
    
)
BEGIN
    DECLARE RESTAURANT_ID_VAR INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error creating food item';
    END;
    
    START TRANSACTION;
    
    INSERT INTO FOOD_ITEMS (RESTAURANT_ID, NAME, PRICE) VALUES (RESTAURANT_ID_IN, FOOD_NAME_IN, PRICE_IN);
    
    COMMIT;
END //

-- Update a food item
DROP PROCEDURE IF EXISTS UPDATE_FOOD_ITEM;
DELIMITER //

CREATE PROCEDURE UPDATE_FOOD_ITEM(
    IN FOOD_ITEM_ID_IN INT,
    IN RESTAURANT_ID_IN INT,
    IN FOOD_NAME_IN VARCHAR(255),
    IN PRICE_IN DECIMAL(6,2)
    
)
BEGIN
    DECLARE RESTAURANT_ID_VAR INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error updating food item';
    END;
    
    START TRANSACTION;
    
    UPDATE FOOD_ITEMS 
    SET RESTAURANT_ID = RESTAURANT_ID_IN, NAME = FOOD_NAME_IN, PRICE = PRICE_IN 
    WHERE FOOD_ITEM_ID = FOOD_ITEM_ID_IN;

    COMMIT;
END //

DELIMITER ;