SELECT O.ORDER_ID, O.ORDER_DATE, CONCAT(TRIM(C.FIRST_NAME), ' ', TRIM(C.LAST_NAME)) AS CUSTOMER_NAME,
R.NAME AS RESTAURANT_NAME, FI.NAME AS FOOD_NAME, FI.PRICE AS ITEM_PRICE
FROM ORDERS AS O
LEFT JOIN FOOD_ITEMS_ORDERS AS FIO
ON O.ORDER_ID = FIO.ORDER_ID
LEFT JOIN FOOD_ITEMS AS FI
ON FIO.FOOD_ITEM_ID = FI.FOOD_ITEM_ID
LEFT JOIN RESTAURANTS AS R
ON FI.RESTAURANT_ID = R.RESTAURANT_ID
LEFT JOIN CUSTOMERS AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY FI.NAME, O.ORDER_ID;
